#!/bin/bash

# get the current directory 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo $DIR

# activate the virtual env
source $DIR/venv/bin/activate

python $DIR/fb.py "$@"